// <auto-generated />
using System;
using Mapping;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mapping.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20250218212354_ArakCreation")]
    partial class ArakCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mapping.Entities.BrailleCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("InstrutorId")
                        .HasColumnType("tinyint");

                    b.Property<string>("LearnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("In Progress");

                    b.HasKey("Id");

                    b.HasIndex("InstrutorId");

                    b.ToTable("BrailleCourses", "BrailleCourse");
                });

            modelBuilder.Entity("Mapping.Entities.BrailleCourseSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BrailleCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrailleCourseId");

                    b.ToTable("BrailleCourseSessions", "BrailleCourse");
                });

            modelBuilder.Entity("Mapping.Entities.Braille_Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("SubjectId")
                        .HasColumnType("tinyint");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TeacherId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("BrailleSession", (string)null);
                });

            modelBuilder.Entity("Mapping.Entities.Grade", b =>
                {
                    b.Property<byte>("GradeID")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LevelID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GradeID");

                    b.HasIndex("LevelID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Mapping.Entities.Instructor", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Instructors", "BrailleCourse");
                });

            modelBuilder.Entity("Mapping.Entities.Level", b =>
                {
                    b.Property<byte>("LevelID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LevelID");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Mapping.Entities.MonthExam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<byte>("MonthNumber")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<byte>("SubjectId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("mark")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("MonthExams");
                });

            modelBuilder.Entity("Mapping.Entities.PrivateBrailleStudents", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PrivateBrailleStudents");
                });

            modelBuilder.Entity("Mapping.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("GradeID")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SubjectId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TeacherId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("GradeID");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Mapping.Entities.SessionAttendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SessionID")
                        .HasColumnType("bigint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionID");

                    b.HasIndex("StudentId");

                    b.ToTable("SessionAttendances");
                });

            modelBuilder.Entity("Mapping.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GradeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("StudentId");

                    b.HasIndex("GradeID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Mapping.Entities.Subject", b =>
                {
                    b.Property<byte>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("SubjectId"));

                    b.Property<byte>("GradeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("TeacherId")
                        .HasColumnType("tinyint");

                    b.HasKey("SubjectId");

                    b.HasIndex("GradeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Mapping.Entities.Teacher", b =>
                {
                    b.Property<byte>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("TeacherId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Mapping.Entities.BrailleCourse", b =>
                {
                    b.HasOne("Mapping.Entities.Instructor", "Instructor")
                        .WithMany("BrailleCourses")
                        .HasForeignKey("InstrutorId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Mapping.Entities.BrailleCourseSession", b =>
                {
                    b.HasOne("Mapping.Entities.BrailleCourse", "BrailleCourse")
                        .WithMany("BrailleCourseSessions")
                        .HasForeignKey("BrailleCourseId");

                    b.Navigation("BrailleCourse");
                });

            modelBuilder.Entity("Mapping.Entities.Braille_Session", b =>
                {
                    b.HasOne("Mapping.Entities.Student", null)
                        .WithMany("BrailleSessions")
                        .HasForeignKey("StudentId");

                    b.HasOne("Mapping.Entities.Subject", null)
                        .WithMany("BrailleSessions")
                        .HasForeignKey("SubjectId");

                    b.HasOne("Mapping.Entities.Teacher", "Teacher")
                        .WithMany("BrailleSessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Mapping.Entities.Grade", b =>
                {
                    b.HasOne("Mapping.Entities.Level", "Level")
                        .WithMany("Grades")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Mapping.Entities.MonthExam", b =>
                {
                    b.HasOne("Mapping.Entities.Student", "Student")
                        .WithMany("MonthExams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mapping.Entities.Subject", "Subject")
                        .WithMany("MonthExams")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Mapping.Entities.Session", b =>
                {
                    b.HasOne("Mapping.Entities.Grade", "Grade")
                        .WithMany("Sessions")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mapping.Entities.Subject", "Subject")
                        .WithMany("Sessions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mapping.Entities.Teacher", "Teacher")
                        .WithMany("Sessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Mapping.Entities.SessionAttendance", b =>
                {
                    b.HasOne("Mapping.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mapping.Entities.Student", "Student")
                        .WithMany("SessionAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Mapping.Entities.Student", b =>
                {
                    b.HasOne("Mapping.Entities.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Mapping.Entities.Subject", b =>
                {
                    b.HasOne("Mapping.Entities.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mapping.Entities.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Grade");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Mapping.Entities.BrailleCourse", b =>
                {
                    b.Navigation("BrailleCourseSessions");
                });

            modelBuilder.Entity("Mapping.Entities.Grade", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Mapping.Entities.Instructor", b =>
                {
                    b.Navigation("BrailleCourses");
                });

            modelBuilder.Entity("Mapping.Entities.Level", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Mapping.Entities.Student", b =>
                {
                    b.Navigation("BrailleSessions");

                    b.Navigation("MonthExams");

                    b.Navigation("SessionAttendances");
                });

            modelBuilder.Entity("Mapping.Entities.Subject", b =>
                {
                    b.Navigation("BrailleSessions");

                    b.Navigation("MonthExams");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Mapping.Entities.Teacher", b =>
                {
                    b.Navigation("BrailleSessions");

                    b.Navigation("Sessions");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
